### ISSUE TITLE
slack registration on site is down

### ISSUE THREAD

**Issue by EloisaSeraphina** [Spectre-Gaming/Spectre-Fleet-Website#23]
The signup form for slack on the website seems to be non-functional.  People who use it are told they are not allowed to sign up for that slack community and have to be invited manually.

**Comment by 5car1z** [comment]
Here's the setting in "Team Settings" that controls this: 

![Sign Ups](https://i.gyazo.com/a862c6c7862be8d0763ccdea40d5e7a9.png)

They might be getting that *not allowed* message if they are trying to sign up with an email address domain that isn't included in that box (my image is an example one btw, not the Spectre one). 

There was also some invitation problems with the TweetFleet Slack a while back, because they had **too many** signups or something. Could be related to that if not this?

**Comment by JayneF** [comment]
You don't want to allow emails from a domain.

Elo, those people using the website form with an out of game browser, can you confirm?

Ibn, any update on this?

**Comment by EloisaSeraphina** [comment]
Yes the ppl were using the out of game browser.  I tested it myself to
double check.
